version: '3.8'
services:
  flask_api:
    container_name: flask_api
    restart: always
    env_file: .env
    build: .
    networks:
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5000:5000"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - flask_api
networks:
  web_network:
    driver: bridge
 